version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:443'
    volumes:
      - './nginx/ssl.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/ssl/server.crt:/etc/nginx/ssl/server.crt'
      - './nginx/ssl/server.key:/etc/nginx/ssl/server.key'
      - './nginx/ssl/server.password:/etc/nginx/ssl/server.password'
      - './lesson-vue:/usr/share/nginx/html'

  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - '.:/lesson-vue'
    tty: true
    stdin_open: true